imports:
  - { resource: parameters.yml }
  - { resource: config.yml }
  - { resource: bundle/nsq.yml }

services:
  cache.app: @doctrine.orm.default_query_cache # array cache for dev
  #cache.app: @cache.glob # uncomment this line for testing cache dependant features

framework:
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true
  profiler: { only_exceptions: false }
  session:
    cookie_domain: "" # allow any cookie domain for development
    cookie_secure: false # allow insecure cookies http://

web_profiler:
  toolbar: true
  intercept_redirects: false

monolog:
  handlers:
    main:
      type:  stream
      path:  %kernel.logs_dir%/%kernel.environment%.log
      level: debug
