parameters:
  # database
  database_driver: '{{ MYSQL_PHP_DRIVER }}'
  database_host: '{{ MYSQL_HOST }}'
  database_port: {{ MYSQL_PORT }}
  database_name: '{{ MYSQL_DATABASE }}'
  database_user: '{{ MYSQL_USER }}'
  database_password: '{{ MYSQL_PASSWORD }}'

  # environment
  locale: en
  secret: ThisTokenIsNotSoSecretChangeIt
  cache_namespace: btc-x
  file_upload_dir: {{ ENV_FILE_UPLOADS_DIR }}
  session_lifetime: 3600 # 1h
  base_url_tag: true
  base_url: '{{ PHP_FRONTEND_BASE_URL }}' # put exmarkets.com base url tag for production
  session_cookie_secure: {{ SESSION_COOKIE_SECURE }}

  # Redis, uses separate databases, max 15, default is 0
  redis_host: '{{ REDIS_HOST }}'
  redis_port: '{{ REDIS_PORT }}'
  redis_db: '{{ REDIS_FRONTEND_DB }}'

  # Host and scheme to use for command context
  router.request_context.host: '{{ ROUTER_HOST }}'
  router.request_context.scheme: '{{ ROUTER_SCHEME }}'

  # mailgun
  mailgun_api_domain: '{{ MAILGUN_API_DOMAIN }}'
  mailgun_api_key: '{{ MAILGUN_API_KEY }}'
  newsletter_email: '{{ MAILGUN_NEWSLETTER_EMAIL }}'
  mailer_from_email: '{{ MAILER_FROM_EMAIL }}'
  mailer_from_name: '{{ MAILER_FROM_NAME }}'
  token_submission_email: '{{ TOKEN_SUBMISSION_EMAIL }}'

  # sentry
  sentry_dsn: '{{ SENTRY_DSN }}'

  # payment core
  pg_egopay_api_wallet_email: '{{ EGOPAY_API_WALLET_EMAIL }}'
  pg_egopay_sci_options_account_id: '{{ EGOPAY_SCI_OPTIONS_ACCOUNT_ID }}'
  pg_egopay_sci_options_account_password: '{{ EGOPAY_SCI_OPTIONS_ACCOUNT_PASSWORD }}'
  pg_egopay_sci_options_success_url: '{{ EGOPAY_SCI_OPTIONS_SUCCESS_URL }}'
  pg_egopay_sci_options_callback_url: '{{ EGOPAY_SCI_OPTIONS_CALLBACK_URL }}'
  pg_egopay_sci_options_fail_url: '{{ EGOPAY_SCI_OPTIONS_FAIL_URL }}'

  pg_payza_sci_options_account_id: "finances@exmarkets.com"
  pg_payza_sci_options_success_url: "btc_account_deposits"
  pg_payza_sci_options_callback_url: "btc_transfer_ipn_receive"
  pg_payza_sci_options_fail_url: "btc_account_deposits"

  pg_okpay_sci_options_account_id: '{{  }}'
  pg_okpay_sci_options_callback_url: "btc_transfer_ipn_receive"

  pg_perfectmoney_sci_options_sci_endpoint: 'https://perfectmoney.is/api/step1.asp'
  pg_perfectmoney_general_usd_account: "{{ PERFECTMONEY_GENERAL_USD_ACCOUNT }}"
  pg_perfectmoney_general_eur_account: "{{ PERFECTMONEY_GENERAL_EUR_ACCOUNT }}"
  pg_perfectmoney_api_credentials_alt_password: "usdacount"
  pg_perfectmoney_sci_options_success_url: "btc_account_deposits"
  pg_perfectmoney_sci_options_callback_url: "btc_transfer_ipn_receive"
  pg_perfectmoney_sci_options_fail_url: "btc_account_deposits"

  pg_astropay_sci_endpoint: "https://www.astropaycard.com/api_curl/apd/"
  pg_astropay_sci_success_url: btc_account_deposits_astropay
  pg_astropay_sci_callback_url: btc_transfer_ipn_receive
  pg_astropay_sci_secret: "fill-in"
  pg_astropay_sci_username: "fill-in"
  pg_astropay_sci_password: "fill-in"
  pg_astropay_api_username: "fill-in"

  vg_btc_api_username: '{{ BTC_API_USERNAME }}'
  vg_btc_api_password: '{{ BTC_API_PASSWORD }}'
  vg_btc_api_hostname: '{{ BTC_API_HOSTNAME }}'
  vg_btc_api_port:     {{ BTC_API_PORT }}
  vg_btc_api_secure:   {{ BTC_API_SECURE }}

  vg_ltc_api_username: '{{ LTC_API_USERNAME }}'
  vg_ltc_api_password: '{{ LTC_API_PASSWORD }}'
  vg_ltc_api_hostname: '{{ LTC_API_HOSTNAME }}'
  vg_ltc_api_port:     {{ LTC_API_PORT }}
  vg_ltc_api_secure:   {{ LTC_API_SECURE }}

  vg_eth_api_username: '{{ ETH_API_USERNAME }}'
  vg_eth_api_password: '{{ ETH_API_PASSWORD }}'
  vg_eth_api_hostname: '{{ ETH_API_HOSTNAME }}'
  vg_eth_api_port:     {{ ETH_API_PORT }}
  vg_eth_api_secure:   {{ ETH_API_SECURE }}

  # orderbook
  orderbook_api_endpoint: '{{ ORDERBOOK_API_ENDPOINT }}'
  websocket_url: '{{ ORDERBOOK_WEBSOCKET_URL }}'

  #twilio
  twilio_from: '{{ TWILIO_FROM }}'
  twilio_sid: '{{ TWILIO_SID }}'
  twilio_token: '{{ TWILIO_TOKEN }}'
  twilio_version: '{{ TWILIO_VERSION }}'

  rest_api_version: {{ REST_API_VERSION }}
  rest_mail_pin_mode: {{ REST_MAIL_PIN_MODE }}

  trade_api_version: 1
  rest_api_debug_mode: 0
  rest_api_debug_user_id: 0
  autodeposit_currency_on_registration: 1
  jwt_private_key: '/app/data/jwt.key'
  jwt_public_key: '/app/data/jwt.key.pub'
  jwt_token_lifetime: 3600
