<?php

namespace Btc\FrontendApiBundle\Classes;

final class RestCodeError
{
    const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
    const INVALID_USERNAME_OR_PASSWORD = 'INVALID_USERNAME_OR_PASSWORD';
    const INVALID_SESSION = 'INVALID_SESSION';
    const INVALID_FILE = 'INVALID_FILE';
    const ACCESS_DENIED = 'ACCESS_DENIED';
    const USER_NOT_FOUND = 'USER_NOT_FOUND';
    const INVALID_PASSWORD = 'INVALID_PASSWORD';
    const VALIDATION_ERROR = 'VALIDATION_ERROR';
    const FEE_ISNT_SET = 'FEE_ISNT_SET';
    const NOT_FOUND = 'NOT_FOUND';
    const BAD_REQUEST = 'BAD_REQUEST';
    const BIG_DELTA = 'BIG_DELTA';
    const HAS_OWN_MATCHING_ORDERS = 'HAS_OWN_MATCHING_ORDERS';
    const ALREADY_EXISTS = 'ALREADY_EXISTS';
    const INCORRECT_DATA = 'INCORRECT_DATA';
    const NO_WALLET = 'NO_WALLET';
    const NO_MARKET = 'NO_MARKET';
    const NOT_ENOUGH_MONEY = 'NOT_ENOUGH_MONEY';
    const NOT_ENOUGH_RESERVED_MONEY = 'NOT_ENOUGH_RESERVED_MONEY';
    const MARKET_MIN_ORDER_QUANTITY_NOT_REACHED = 'MARKET_MIN_ORDER_QUANTITY_NOT_REACHED';
    const MARKET_EMPTY = 'MARKET_EMPTY';
    const ORDER_VALUE_TOO_LOW = 'ORDER_VALUE_TOO_LOW';
    const TWO_FACTOR_AUTH_DISABLED = 'TWO_FACTOR_AUTH_DISABLED';
    const OPTIMISTIC_LOCK_FAILED = 'OPTIMISTIC_LOCK_FAILED';
    const ORDER_INVALID_PRICE = 'ORDER_INVALID_PRICE';
    const TOO_OFTEN_ADDRESS_REQUEST = 'TOO_OFTEN_ADDRESS_REQUEST';
    const NOT_UPLOADED_FILE = 'NOT_UPLOADED_FILE';
    const USER_ALREADY_DECLINED = 'USER_ALREADY_DECLINED';
    const UNKNOWN_OHLCV_INTERVAL = 'UNKNOWN_OHLCV_INTERVAL';
    const USER_BLOCKED = 'USER_BLOCKED';
    const VERIFICATION_PENDING = 'VERIFICATION_PENDING';
    const HOTP_SENT_TIMES_EXCEEDED = 'HOTP_SENT_TIMES_EXCEEDED';
    const INVALID_TOKEN = 'INVALID_TOKEN';
    const ORDER_ALREADY_COMPLETED = 'ORDER_ALREADY_COMPLETED';
    const ORDER_ALREADY_CANCELLED = 'ORDER_ALREADY_CANCELLED';
    const DB_DEFAULT_ERROR = 'DB_DEFAULT_ERROR';
}
